class ArmConstants():

    WAIST_CHANNEL = 0
    WAIST_MIN_PULSE = 500
    WAIST_MAX_PULSE = 2500
    WAIST_REST_ANGLE = 90

    SHOULDER_CHANNEL = 1
    SHOULDER_MIN_PULSE = 500
    SHOULDER_MAX_PULSE = 2500
    SHOULDER_REST_ANGLE = 90

    ELBOW_CHANNEL = 2
    ELBOW_MIN_PULSE = 500
    ELBOW_MAX_PULSE = 2500
    ELBOW_REST_ANGLE = 90

    WRIST_CHANNEL = 3
    WRIST_MIN_PULSE = 500
    WRIST_MAX_PULSE = 2500
    WRIST_REST_ANGLE = 90

    END_EFFECTOR_CHANNEL = 4
    END_EFFECTOR_MIN_PULSE = 500
    END_EFFECTOR_MAX_PULSE = 2500
    END_EFFECTOR_REST_ANGLE = 90
    